spring:
  config:
    activate:
      on-profile: dev
  graphql:
    graphiql:
      enabled: true

datasource:
  postgres:
    host: localhost
    port: 5432
    dbname: reece
    username: reece
    password: reece