version: '3.5'

services:

  addressbook:
    container_name: ms-address-book_container
    image: ashkanfarivarmoheb/addressbook
    links:
      - postgres-db
    ports:
      - "8090:8090"
    env_file:
      - docker-se-dev.env

  postgres-db:
    image: postgres
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reece"]
      interval: 15s
      timeout: 5s
      retries: 10
    ulimits:
      nproc: 65545
    ports:
      - "5432:5432"
    env_file:
      - docker-psql-dev.env
    restart: unless-stopped

